sonar.projectKey=vdovetzi_oge
sonar.organization=vdovetzi
sonar.projectName=Occupancy Grid Editor
sonar.sourceEncoding=UTF-8
sonar.sources=oge
sonar.tests=tests
sonar.python.version=3.10,3.11,3.12,3.13
sonar.python.coverage.reportPaths=coverage.xml
